// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_analyses.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIAnalysis = `-- name: CreateAIAnalysis :one
INSERT INTO ai_analyses (user_id, content_id, summary, strengths, improvements, score)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, content_id, summary, strengths, improvements, score, created_at, updated_at
`

type CreateAIAnalysisParams struct {
	UserID       pgtype.UUID
	ContentID    pgtype.UUID
	Summary      string
	Strengths    []byte
	Improvements []byte
	Score        int32
}

func (q *Queries) CreateAIAnalysis(ctx context.Context, arg CreateAIAnalysisParams) (AiAnalysis, error) {
	row := q.db.QueryRow(ctx, createAIAnalysis,
		arg.UserID,
		arg.ContentID,
		arg.Summary,
		arg.Strengths,
		arg.Improvements,
		arg.Score,
	)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentID,
		&i.Summary,
		&i.Strengths,
		&i.Improvements,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestAnalysisByContent = `-- name: GetLatestAnalysisByContent :one
SELECT id, user_id, content_id, summary, strengths, improvements, score, created_at, updated_at FROM ai_analyses
WHERE content_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAnalysisByContentParams struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetLatestAnalysisByContent(ctx context.Context, arg GetLatestAnalysisByContentParams) (AiAnalysis, error) {
	row := q.db.QueryRow(ctx, getLatestAnalysisByContent, arg.ContentID, arg.UserID)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentID,
		&i.Summary,
		&i.Strengths,
		&i.Improvements,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
