// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rodrigo-militao/forge/internal/core/domain"
)

const addArticleCategory = `-- name: AddArticleCategory :exec
INSERT INTO article_categories (category_id, article_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddArticleCategoryParams struct {
	CategoryID pgtype.UUID
	ArticleID  pgtype.UUID
}

func (q *Queries) AddArticleCategory(ctx context.Context, arg AddArticleCategoryParams) error {
	_, err := q.db.Exec(ctx, addArticleCategory, arg.CategoryID, arg.ArticleID)
	return err
}

const addArticleCategoryArray = `-- name: AddArticleCategoryArray :one
UPDATE generated_content
SET categories = array_append(categories, $2), updated_at = now()
WHERE id = $1 AND NOT ($2 = ANY(categories))
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type AddArticleCategoryArrayParams struct {
	ID          pgtype.UUID
	ArrayAppend interface{}
}

func (q *Queries) AddArticleCategoryArray(ctx context.Context, arg AddArticleCategoryArrayParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, addArticleCategoryArray, arg.ID, arg.ArrayAppend)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const addContentTagArray = `-- name: AddContentTagArray :one
UPDATE generated_content
SET tags = array_append(tags, $2), updated_at = now()
WHERE id = $1 AND NOT ($2 = ANY(tags))
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type AddContentTagArrayParams struct {
	ID          pgtype.UUID
	ArrayAppend interface{}
}

func (q *Queries) AddContentTagArray(ctx context.Context, arg AddContentTagArrayParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, addContentTagArray, arg.ID, arg.ArrayAppend)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const addContentTagJunction = `-- name: AddContentTagJunction :exec
INSERT INTO content_tags (tag_id, content_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddContentTagJunctionParams struct {
	TagID     pgtype.UUID
	ContentID pgtype.UUID
}

func (q *Queries) AddContentTagJunction(ctx context.Context, arg AddContentTagJunctionParams) error {
	_, err := q.db.Exec(ctx, addContentTagJunction, arg.TagID, arg.ContentID)
	return err
}

const addDigestArticleTag = `-- name: AddDigestArticleTag :exec
INSERT INTO digest_article_tags (tag_id, article_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDigestArticleTagParams struct {
	TagID     pgtype.UUID
	ArticleID pgtype.UUID
}

func (q *Queries) AddDigestArticleTag(ctx context.Context, arg AddDigestArticleTagParams) error {
	_, err := q.db.Exec(ctx, addDigestArticleTag, arg.TagID, arg.ArticleID)
	return err
}

const contentExistsByURL = `-- name: ContentExistsByURL :one
SELECT EXISTS(
  SELECT 1 FROM generated_content
  WHERE user_id = $1 AND metadata->>'source_url' = $2::text
) AS found
`

type ContentExistsByURLParams struct {
	UserID  pgtype.UUID
	Column2 string
}

func (q *Queries) ContentExistsByURL(ctx context.Context, arg ContentExistsByURLParams) (bool, error) {
	row := q.db.QueryRow(ctx, contentExistsByURL, arg.UserID, arg.Column2)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const createContent = `-- name: CreateContent :one

INSERT INTO generated_content (user_id, product, status, source_type, title, body_markdown, metadata, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type CreateContentParams struct {
	UserID       pgtype.UUID
	Product      domain.ContentProduct
	Status       domain.ContentStatus
	SourceType   *string
	Title        *string
	BodyMarkdown *string
	Metadata     []byte
	Origin       string
}

// Generated content
func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.UserID,
		arg.Product,
		arg.Status,
		arg.SourceType,
		arg.Title,
		arg.BodyMarkdown,
		arg.Metadata,
		arg.Origin,
	)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const ensureCategory = `-- name: EnsureCategory :one

INSERT INTO categories (user_id, label)
VALUES ($1, $2)
ON CONFLICT (user_id, label) DO NOTHING
RETURNING id, user_id, label, created_at
`

type EnsureCategoryParams struct {
	UserID pgtype.UUID
	Label  string
}

// =============================================================================
// Categories (ADR 0045)
// =============================================================================
func (q *Queries) EnsureCategory(ctx context.Context, arg EnsureCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, ensureCategory, arg.UserID, arg.Label)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const ensureTag = `-- name: EnsureTag :one
INSERT INTO tags (user_id, label)
VALUES ($1, $2)
ON CONFLICT (user_id, label) DO NOTHING
RETURNING id, user_id, label, created_at
`

type EnsureTagParams struct {
	UserID pgtype.UUID
	Label  string
}

func (q *Queries) EnsureTag(ctx context.Context, arg EnsureTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, ensureTag, arg.UserID, arg.Label)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByLabel = `-- name: GetCategoryByLabel :one
SELECT id, user_id, label, created_at FROM categories
WHERE user_id = $1 AND label = $2
`

type GetCategoryByLabelParams struct {
	UserID pgtype.UUID
	Label  string
}

func (q *Queries) GetCategoryByLabel(ctx context.Context, arg GetCategoryByLabelParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByLabel, arg.UserID, arg.Label)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories FROM generated_content WHERE id = $1
`

func (q *Queries) GetContentByID(ctx context.Context, id pgtype.UUID) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const getDigestStats = `-- name: GetDigestStats :one

SELECT
  COALESCE(art.total_count, 0)::int AS total_count,
  COALESCE(art.in_newsletter_count, 0)::int AS in_newsletter_count,
  art.last_discovery AS last_discovery,
  COALESCE(ne.draft_count, 0)::int AS draft_newsletters
FROM (
  SELECT
    COUNT(*) AS total_count,
    COUNT(*) FILTER (WHERE gc.id IN (SELECT na.digest_article_id FROM newsletter_articles na)) AS in_newsletter_count,
    MAX(gc.created_at) AS last_discovery
  FROM generated_content gc
  WHERE gc.user_id = $1 AND gc.product = 'digest' AND gc.deleted_at IS NULL
) art
CROSS JOIN (
  SELECT COUNT(*) AS draft_count
  FROM newsletter_editions
  WHERE user_id = $1 AND status = 'draft'
) ne
`

type GetDigestStatsRow struct {
	TotalCount        int32
	InNewsletterCount int32
	LastDiscovery     interface{}
	DraftNewsletters  int32
}

// =============================================================================
// Digest stats (Phase 2)
// =============================================================================
func (q *Queries) GetDigestStats(ctx context.Context, userID pgtype.UUID) (GetDigestStatsRow, error) {
	row := q.db.QueryRow(ctx, getDigestStats, userID)
	var i GetDigestStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.InNewsletterCount,
		&i.LastDiscovery,
		&i.DraftNewsletters,
	)
	return i, err
}

const getTagByLabel = `-- name: GetTagByLabel :one
SELECT id, user_id, label, created_at FROM tags
WHERE user_id = $1 AND label = $2
`

type GetTagByLabelParams struct {
	UserID pgtype.UUID
	Label  string
}

func (q *Queries) GetTagByLabel(ctx context.Context, arg GetTagByLabelParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByLabel, arg.UserID, arg.Label)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCategoriesByUser = `-- name: ListAllCategoriesByUser :many
SELECT DISTINCT label FROM categories
WHERE user_id = $1
ORDER BY label
`

func (q *Queries) ListAllCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleCategories = `-- name: ListArticleCategories :many
SELECT c.label FROM article_categories ac
JOIN categories c ON c.id = ac.category_id
WHERE ac.article_id = $1
ORDER BY c.label
`

func (q *Queries) ListArticleCategories(ctx context.Context, articleID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listArticleCategories, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentByUser = `-- name: ListContentByUser :many
SELECT id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories FROM generated_content
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContentByUser(ctx context.Context, userID pgtype.UUID) ([]GeneratedContent, error) {
	rows, err := q.db.Query(ctx, listContentByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedContent
	for rows.Next() {
		var i GeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Product,
			&i.Status,
			&i.SourceType,
			&i.Title,
			&i.BodyMarkdown,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.DeletedAt,
			&i.Category,
			&i.Tags,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentWithoutCategory = `-- name: ListContentWithoutCategory :many
SELECT id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories FROM generated_content
WHERE user_id = $1 AND product = 'digest' AND categories = '{}' AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListContentWithoutCategoryParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListContentWithoutCategory(ctx context.Context, arg ListContentWithoutCategoryParams) ([]GeneratedContent, error) {
	rows, err := q.db.Query(ctx, listContentWithoutCategory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedContent
	for rows.Next() {
		var i GeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Product,
			&i.Status,
			&i.SourceType,
			&i.Title,
			&i.BodyMarkdown,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.DeletedAt,
			&i.Category,
			&i.Tags,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCategories = `-- name: ListUserCategories :many
SELECT label FROM categories
WHERE user_id = $1
ORDER BY label
`

func (q *Queries) ListUserCategories(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTags = `-- name: ListUserTags :many
SELECT label FROM tags
WHERE user_id = $1
ORDER BY label
`

func (q *Queries) ListUserTags(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArticleCategory = `-- name: RemoveArticleCategory :exec
DELETE FROM article_categories
WHERE category_id = $1 AND article_id = $2
`

type RemoveArticleCategoryParams struct {
	CategoryID pgtype.UUID
	ArticleID  pgtype.UUID
}

func (q *Queries) RemoveArticleCategory(ctx context.Context, arg RemoveArticleCategoryParams) error {
	_, err := q.db.Exec(ctx, removeArticleCategory, arg.CategoryID, arg.ArticleID)
	return err
}

const removeArticleCategoryArray = `-- name: RemoveArticleCategoryArray :one
UPDATE generated_content
SET categories = array_remove(categories, $2), updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type RemoveArticleCategoryArrayParams struct {
	ID          pgtype.UUID
	ArrayRemove interface{}
}

func (q *Queries) RemoveArticleCategoryArray(ctx context.Context, arg RemoveArticleCategoryArrayParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, removeArticleCategoryArray, arg.ID, arg.ArrayRemove)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const removeContentTagArray = `-- name: RemoveContentTagArray :one
UPDATE generated_content
SET tags = array_remove(tags, $2), updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type RemoveContentTagArrayParams struct {
	ID          pgtype.UUID
	ArrayRemove interface{}
}

func (q *Queries) RemoveContentTagArray(ctx context.Context, arg RemoveContentTagArrayParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, removeContentTagArray, arg.ID, arg.ArrayRemove)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const removeContentTagJunction = `-- name: RemoveContentTagJunction :exec
DELETE FROM content_tags
WHERE tag_id = $1 AND content_id = $2
`

type RemoveContentTagJunctionParams struct {
	TagID     pgtype.UUID
	ContentID pgtype.UUID
}

func (q *Queries) RemoveContentTagJunction(ctx context.Context, arg RemoveContentTagJunctionParams) error {
	_, err := q.db.Exec(ctx, removeContentTagJunction, arg.TagID, arg.ContentID)
	return err
}

const removeDigestArticleTag = `-- name: RemoveDigestArticleTag :exec
DELETE FROM digest_article_tags
WHERE tag_id = $1 AND article_id = $2
`

type RemoveDigestArticleTagParams struct {
	TagID     pgtype.UUID
	ArticleID pgtype.UUID
}

func (q *Queries) RemoveDigestArticleTag(ctx context.Context, arg RemoveDigestArticleTagParams) error {
	_, err := q.db.Exec(ctx, removeDigestArticleTag, arg.TagID, arg.ArticleID)
	return err
}

const softDeleteContent = `-- name: SoftDeleteContent :one
UPDATE generated_content
SET deleted_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

func (q *Queries) SoftDeleteContent(ctx context.Context, id pgtype.UUID) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, softDeleteContent, id)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const updateContentBody = `-- name: UpdateContentBody :one
UPDATE generated_content
SET title = COALESCE($2, title), body_markdown = COALESCE($3, body_markdown), updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type UpdateContentBodyParams struct {
	ID           pgtype.UUID
	Title        *string
	BodyMarkdown *string
}

func (q *Queries) UpdateContentBody(ctx context.Context, arg UpdateContentBodyParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, updateContentBody, arg.ID, arg.Title, arg.BodyMarkdown)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}

const updateContentStatus = `-- name: UpdateContentStatus :one
UPDATE generated_content
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin, deleted_at, category, tags, categories
`

type UpdateContentStatusParams struct {
	ID     pgtype.UUID
	Status domain.ContentStatus
}

func (q *Queries) UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, updateContentStatus, arg.ID, arg.Status)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.DeletedAt,
		&i.Category,
		&i.Tags,
		&i.Categories,
	)
	return i, err
}
