// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rodrigo-militao/forge/internal/core/domain"
)

const createContent = `-- name: CreateContent :one

INSERT INTO generated_content (user_id, product, status, source_type, title, body_markdown, metadata, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin
`

type CreateContentParams struct {
	UserID       pgtype.UUID
	Product      domain.ContentProduct
	Status       domain.ContentStatus
	SourceType   *string
	Title        *string
	BodyMarkdown *string
	Metadata     []byte
	Origin       string
}

// Generated content
func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.UserID,
		arg.Product,
		arg.Status,
		arg.SourceType,
		arg.Title,
		arg.BodyMarkdown,
		arg.Metadata,
		arg.Origin,
	)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin FROM generated_content WHERE id = $1
`

func (q *Queries) GetContentByID(ctx context.Context, id pgtype.UUID) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
	)
	return i, err
}

const listApprovedDigest = `-- name: ListApprovedDigest :many
SELECT gc.id, gc.user_id, gc.product, gc.status, gc.source_type, gc.title, gc.body_markdown, gc.metadata, gc.created_at, gc.updated_at, gc.origin FROM generated_content gc
WHERE gc.user_id = $1
  AND gc.product = 'digest'
  AND gc.status = 'approved'
ORDER BY gc.updated_at DESC
`

func (q *Queries) ListApprovedDigest(ctx context.Context, userID pgtype.UUID) ([]GeneratedContent, error) {
	rows, err := q.db.Query(ctx, listApprovedDigest, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedContent
	for rows.Next() {
		var i GeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Product,
			&i.Status,
			&i.SourceType,
			&i.Title,
			&i.BodyMarkdown,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentByUser = `-- name: ListContentByUser :many
SELECT id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin FROM generated_content
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContentByUser(ctx context.Context, userID pgtype.UUID) ([]GeneratedContent, error) {
	rows, err := q.db.Query(ctx, listContentByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedContent
	for rows.Next() {
		var i GeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Product,
			&i.Status,
			&i.SourceType,
			&i.Title,
			&i.BodyMarkdown,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentBody = `-- name: UpdateContentBody :one
UPDATE generated_content
SET title = COALESCE($2, title), body_markdown = COALESCE($3, body_markdown), updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin
`

type UpdateContentBodyParams struct {
	ID           pgtype.UUID
	Title        *string
	BodyMarkdown *string
}

func (q *Queries) UpdateContentBody(ctx context.Context, arg UpdateContentBodyParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, updateContentBody, arg.ID, arg.Title, arg.BodyMarkdown)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
	)
	return i, err
}

const updateContentStatus = `-- name: UpdateContentStatus :one
UPDATE generated_content
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, product, status, source_type, title, body_markdown, metadata, created_at, updated_at, origin
`

type UpdateContentStatusParams struct {
	ID     pgtype.UUID
	Status domain.ContentStatus
}

func (q *Queries) UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, updateContentStatus, arg.ID, arg.Status)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.SourceType,
		&i.Title,
		&i.BodyMarkdown,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
	)
	return i, err
}
