// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest_interests.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDigestInterest = `-- name: CreateDigestInterest :one
INSERT INTO digest_interests (user_id, label)
VALUES ($1, $2)
RETURNING id, user_id, label, created_at
`

type CreateDigestInterestParams struct {
	UserID pgtype.UUID
	Label  string
}

func (q *Queries) CreateDigestInterest(ctx context.Context, arg CreateDigestInterestParams) (DigestInterest, error) {
	row := q.db.QueryRow(ctx, createDigestInterest, arg.UserID, arg.Label)
	var i DigestInterest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDigestInterest = `-- name: DeleteDigestInterest :one
DELETE FROM digest_interests WHERE id = $1 AND user_id = $2
RETURNING id, user_id, label, created_at
`

type DeleteDigestInterestParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteDigestInterest(ctx context.Context, arg DeleteDigestInterestParams) (DigestInterest, error) {
	row := q.db.QueryRow(ctx, deleteDigestInterest, arg.ID, arg.UserID)
	var i DigestInterest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listDigestInterests = `-- name: ListDigestInterests :many

SELECT id, user_id, label, created_at FROM digest_interests WHERE user_id = $1 ORDER BY label
`

// Digest interests (ADR 0032)
func (q *Queries) ListDigestInterests(ctx context.Context, userID pgtype.UUID) ([]DigestInterest, error) {
	rows, err := q.db.Query(ctx, listDigestInterests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DigestInterest
	for rows.Next() {
		var i DigestInterest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
