// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNewsletterArticle = `-- name: AddNewsletterArticle :exec
INSERT INTO newsletter_articles (newsletter_id, digest_article_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddNewsletterArticleParams struct {
	NewsletterID    pgtype.UUID
	DigestArticleID pgtype.UUID
}

func (q *Queries) AddNewsletterArticle(ctx context.Context, arg AddNewsletterArticleParams) error {
	_, err := q.db.Exec(ctx, addNewsletterArticle, arg.NewsletterID, arg.DigestArticleID)
	return err
}

const addNewsletterEditionTag = `-- name: AddNewsletterEditionTag :exec
INSERT INTO newsletter_edition_tags (edition_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddNewsletterEditionTagParams struct {
	EditionID pgtype.UUID
	TagID     pgtype.UUID
}

// Newsletter edition tags
func (q *Queries) AddNewsletterEditionTag(ctx context.Context, arg AddNewsletterEditionTagParams) error {
	_, err := q.db.Exec(ctx, addNewsletterEditionTag, arg.EditionID, arg.TagID)
	return err
}

const createEdition = `-- name: CreateEdition :one
INSERT INTO newsletter_editions (user_id, title, introduction, category, destination)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, introduction, status, created_at, updated_at, category, destination
`

type CreateEditionParams struct {
	UserID       pgtype.UUID
	Title        string
	Introduction string
	Category     *string
	Destination  *string
}

// Newsletter editions (ADR 0029)
func (q *Queries) CreateEdition(ctx context.Context, arg CreateEditionParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, createEdition,
		arg.UserID,
		arg.Title,
		arg.Introduction,
		arg.Category,
		arg.Destination,
	)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}

const duplicateEdition = `-- name: DuplicateEdition :one
INSERT INTO newsletter_editions (user_id, title, destination)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, introduction, status, created_at, updated_at, category, destination
`

type DuplicateEditionParams struct {
	UserID      pgtype.UUID
	Title       string
	Destination *string
}

func (q *Queries) DuplicateEdition(ctx context.Context, arg DuplicateEditionParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, duplicateEdition, arg.UserID, arg.Title, arg.Destination)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}

const getEditionByID = `-- name: GetEditionByID :one
SELECT id, user_id, title, introduction, status, created_at, updated_at, category, destination FROM newsletter_editions WHERE id = $1
`

func (q *Queries) GetEditionByID(ctx context.Context, id pgtype.UUID) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, getEditionByID, id)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}

const listArticleCountsByEditionIDs = `-- name: ListArticleCountsByEditionIDs :many
SELECT na.newsletter_id, COUNT(*)::INT as article_count
FROM newsletter_articles na
WHERE na.newsletter_id = ANY($1::UUID[])
GROUP BY na.newsletter_id
`

type ListArticleCountsByEditionIDsRow struct {
	NewsletterID pgtype.UUID
	ArticleCount int32
}

func (q *Queries) ListArticleCountsByEditionIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListArticleCountsByEditionIDsRow, error) {
	rows, err := q.db.Query(ctx, listArticleCountsByEditionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleCountsByEditionIDsRow
	for rows.Next() {
		var i ListArticleCountsByEditionIDsRow
		if err := rows.Scan(&i.NewsletterID, &i.ArticleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleIDsInAnyNewsletter = `-- name: ListArticleIDsInAnyNewsletter :many

SELECT DISTINCT na.digest_article_id
FROM newsletter_articles na
JOIN newsletter_editions ne ON na.newsletter_id = ne.id
WHERE ne.user_id = $1
`

// Edition items (removed — replaced by newsletter_articles in ADR 0043)
func (q *Queries) ListArticleIDsInAnyNewsletter(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listArticleIDsInAnyNewsletter, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var digest_article_id pgtype.UUID
		if err := rows.Scan(&digest_article_id); err != nil {
			return nil, err
		}
		items = append(items, digest_article_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditionsByUser = `-- name: ListEditionsByUser :many
SELECT id, user_id, title, introduction, status, created_at, updated_at, category, destination FROM newsletter_editions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEditionsByUser(ctx context.Context, userID pgtype.UUID) ([]NewsletterEdition, error) {
	rows, err := q.db.Query(ctx, listEditionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterEdition
	for rows.Next() {
		var i NewsletterEdition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Introduction,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditionsByUserFiltered = `-- name: ListEditionsByUserFiltered :many
SELECT id, user_id, title, introduction, status, created_at, updated_at, category, destination FROM newsletter_editions
WHERE user_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TEXT IS NULL OR category = $3)
ORDER BY created_at DESC
`

type ListEditionsByUserFilteredParams struct {
	UserID         pgtype.UUID
	StatusFilter   *string
	CategoryFilter *string
}

func (q *Queries) ListEditionsByUserFiltered(ctx context.Context, arg ListEditionsByUserFilteredParams) ([]NewsletterEdition, error) {
	rows, err := q.db.Query(ctx, listEditionsByUserFiltered, arg.UserID, arg.StatusFilter, arg.CategoryFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterEdition
	for rows.Next() {
		var i NewsletterEdition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Introduction,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterArticlesByEditionID = `-- name: ListNewsletterArticlesByEditionID :many
SELECT na.digest_article_id, na.added_at, gc.title, gc.body_markdown
FROM newsletter_articles na
JOIN generated_content gc ON na.digest_article_id = gc.id
WHERE na.newsletter_id = $1
ORDER BY na.added_at
`

type ListNewsletterArticlesByEditionIDRow struct {
	DigestArticleID pgtype.UUID
	AddedAt         pgtype.Timestamptz
	Title           *string
	BodyMarkdown    *string
}

func (q *Queries) ListNewsletterArticlesByEditionID(ctx context.Context, newsletterID pgtype.UUID) ([]ListNewsletterArticlesByEditionIDRow, error) {
	rows, err := q.db.Query(ctx, listNewsletterArticlesByEditionID, newsletterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsletterArticlesByEditionIDRow
	for rows.Next() {
		var i ListNewsletterArticlesByEditionIDRow
		if err := rows.Scan(
			&i.DigestArticleID,
			&i.AddedAt,
			&i.Title,
			&i.BodyMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterEditionTags = `-- name: ListNewsletterEditionTags :many
SELECT t.label FROM newsletter_edition_tags net
JOIN tags t ON t.id = net.tag_id
WHERE net.edition_id = $1
ORDER BY t.label
`

func (q *Queries) ListNewsletterEditionTags(ctx context.Context, editionID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listNewsletterEditionTags, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterEditionTagsByEditionIDs = `-- name: ListNewsletterEditionTagsByEditionIDs :many
SELECT net.edition_id, t.label FROM newsletter_edition_tags net
JOIN tags t ON t.id = net.tag_id
WHERE net.edition_id = ANY($1::UUID[])
ORDER BY t.label
`

type ListNewsletterEditionTagsByEditionIDsRow struct {
	EditionID pgtype.UUID
	Label     string
}

func (q *Queries) ListNewsletterEditionTagsByEditionIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListNewsletterEditionTagsByEditionIDsRow, error) {
	rows, err := q.db.Query(ctx, listNewsletterEditionTagsByEditionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsletterEditionTagsByEditionIDsRow
	for rows.Next() {
		var i ListNewsletterEditionTagsByEditionIDsRow
		if err := rows.Scan(&i.EditionID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedDestinationsByUser = `-- name: ListUsedDestinationsByUser :many
SELECT DISTINCT destination FROM newsletter_editions
WHERE user_id = $1 AND destination IS NOT NULL AND destination <> ''
ORDER BY destination
`

func (q *Queries) ListUsedDestinationsByUser(ctx context.Context, userID pgtype.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listUsedDestinationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var destination *string
		if err := rows.Scan(&destination); err != nil {
			return nil, err
		}
		items = append(items, destination)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNewsletterArticle = `-- name: RemoveNewsletterArticle :exec
DELETE FROM newsletter_articles
WHERE newsletter_id = $1 AND digest_article_id = $2
`

type RemoveNewsletterArticleParams struct {
	NewsletterID    pgtype.UUID
	DigestArticleID pgtype.UUID
}

func (q *Queries) RemoveNewsletterArticle(ctx context.Context, arg RemoveNewsletterArticleParams) error {
	_, err := q.db.Exec(ctx, removeNewsletterArticle, arg.NewsletterID, arg.DigestArticleID)
	return err
}

const removeNewsletterEditionTag = `-- name: RemoveNewsletterEditionTag :exec
DELETE FROM newsletter_edition_tags
WHERE edition_id = $1 AND tag_id = $2
`

type RemoveNewsletterEditionTagParams struct {
	EditionID pgtype.UUID
	TagID     pgtype.UUID
}

func (q *Queries) RemoveNewsletterEditionTag(ctx context.Context, arg RemoveNewsletterEditionTagParams) error {
	_, err := q.db.Exec(ctx, removeNewsletterEditionTag, arg.EditionID, arg.TagID)
	return err
}

const updateEditionBody = `-- name: UpdateEditionBody :one
UPDATE newsletter_editions
SET title = $2, introduction = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, introduction, status, created_at, updated_at, category, destination
`

type UpdateEditionBodyParams struct {
	ID           pgtype.UUID
	Title        string
	Introduction string
}

func (q *Queries) UpdateEditionBody(ctx context.Context, arg UpdateEditionBodyParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, updateEditionBody, arg.ID, arg.Title, arg.Introduction)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}

const updateEditionCategory = `-- name: UpdateEditionCategory :one
UPDATE newsletter_editions
SET category = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, introduction, status, created_at, updated_at, category, destination
`

type UpdateEditionCategoryParams struct {
	ID       pgtype.UUID
	Category *string
}

func (q *Queries) UpdateEditionCategory(ctx context.Context, arg UpdateEditionCategoryParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, updateEditionCategory, arg.ID, arg.Category)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}

const updateEditionDestination = `-- name: UpdateEditionDestination :one
UPDATE newsletter_editions
SET destination = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, introduction, status, created_at, updated_at, category, destination
`

type UpdateEditionDestinationParams struct {
	ID          pgtype.UUID
	Destination *string
}

func (q *Queries) UpdateEditionDestination(ctx context.Context, arg UpdateEditionDestinationParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, updateEditionDestination, arg.ID, arg.Destination)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}

const updateEditionStatus = `-- name: UpdateEditionStatus :one
UPDATE newsletter_editions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, introduction, status, created_at, updated_at, category, destination
`

type UpdateEditionStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateEditionStatus(ctx context.Context, arg UpdateEditionStatusParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, updateEditionStatus, arg.ID, arg.Status)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Destination,
	)
	return i, err
}
