// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEdition = `-- name: CreateEdition :one
INSERT INTO newsletter_editions (user_id, title, introduction)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, introduction, status, created_at, updated_at
`

type CreateEditionParams struct {
	UserID       pgtype.UUID
	Title        string
	Introduction string
}

// Newsletter editions (ADR 0029)
func (q *Queries) CreateEdition(ctx context.Context, arg CreateEditionParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, createEdition, arg.UserID, arg.Title, arg.Introduction)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEditionItem = `-- name: CreateEditionItem :one
INSERT INTO newsletter_edition_items (edition_id, content_id, sort_order)
VALUES ($1, $2, $3)
RETURNING id, edition_id, content_id, sort_order, created_at
`

type CreateEditionItemParams struct {
	EditionID pgtype.UUID
	ContentID pgtype.UUID
	SortOrder int32
}

// Edition items
func (q *Queries) CreateEditionItem(ctx context.Context, arg CreateEditionItemParams) (NewsletterEditionItem, error) {
	row := q.db.QueryRow(ctx, createEditionItem, arg.EditionID, arg.ContentID, arg.SortOrder)
	var i NewsletterEditionItem
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.ContentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getEditionByID = `-- name: GetEditionByID :one
SELECT id, user_id, title, introduction, status, created_at, updated_at FROM newsletter_editions WHERE id = $1
`

func (q *Queries) GetEditionByID(ctx context.Context, id pgtype.UUID) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, getEditionByID, id)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEditionItems = `-- name: ListEditionItems :many
SELECT id, edition_id, content_id, sort_order, created_at FROM newsletter_edition_items
WHERE edition_id = $1
ORDER BY sort_order
`

func (q *Queries) ListEditionItems(ctx context.Context, editionID pgtype.UUID) ([]NewsletterEditionItem, error) {
	rows, err := q.db.Query(ctx, listEditionItems, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterEditionItem
	for rows.Next() {
		var i NewsletterEditionItem
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.ContentID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditionsByUser = `-- name: ListEditionsByUser :many
SELECT id, user_id, title, introduction, status, created_at, updated_at FROM newsletter_editions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEditionsByUser(ctx context.Context, userID pgtype.UUID) ([]NewsletterEdition, error) {
	rows, err := q.db.Query(ctx, listEditionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterEdition
	for rows.Next() {
		var i NewsletterEdition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Introduction,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedContentIDs = `-- name: ListUsedContentIDs :many
SELECT DISTINCT nei.content_id
FROM newsletter_edition_items nei
JOIN newsletter_editions ne ON nei.edition_id = ne.id
WHERE ne.user_id = $1
`

func (q *Queries) ListUsedContentIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUsedContentIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var content_id pgtype.UUID
		if err := rows.Scan(&content_id); err != nil {
			return nil, err
		}
		items = append(items, content_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEditionBody = `-- name: UpdateEditionBody :one
UPDATE newsletter_editions
SET title = $2, introduction = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, introduction, status, created_at, updated_at
`

type UpdateEditionBodyParams struct {
	ID           pgtype.UUID
	Title        string
	Introduction string
}

func (q *Queries) UpdateEditionBody(ctx context.Context, arg UpdateEditionBodyParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, updateEditionBody, arg.ID, arg.Title, arg.Introduction)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEditionStatus = `-- name: UpdateEditionStatus :one
UPDATE newsletter_editions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, introduction, status, created_at, updated_at
`

type UpdateEditionStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateEditionStatus(ctx context.Context, arg UpdateEditionStatusParams) (NewsletterEdition, error) {
	row := q.db.QueryRow(ctx, updateEditionStatus, arg.ID, arg.Status)
	var i NewsletterEdition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Introduction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
