// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ideas.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIdeaArticle = `-- name: AddIdeaArticle :exec
INSERT INTO idea_articles (idea_id, content_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIdeaArticleParams struct {
	IdeaID    pgtype.UUID
	ContentID pgtype.UUID
}

func (q *Queries) AddIdeaArticle(ctx context.Context, arg AddIdeaArticleParams) error {
	_, err := q.db.Exec(ctx, addIdeaArticle, arg.IdeaID, arg.ContentID)
	return err
}

const addIdeaTag = `-- name: AddIdeaTag :exec
INSERT INTO idea_tags (tag_id, idea_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIdeaTagParams struct {
	TagID  pgtype.UUID
	IdeaID pgtype.UUID
}

func (q *Queries) AddIdeaTag(ctx context.Context, arg AddIdeaTagParams) error {
	_, err := q.db.Exec(ctx, addIdeaTag, arg.TagID, arg.IdeaID)
	return err
}

const createIdea = `-- name: CreateIdea :one

INSERT INTO ideas (user_id, title, context, notes, "references", priority, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, context, notes, "references", priority, status, created_at, updated_at, source_digest_article_id
`

type CreateIdeaParams struct {
	UserID     pgtype.UUID
	Title      string
	Context    *string
	Notes      *string
	References *string
	Priority   string
	Status     string
}

// Ideas
func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (Idea, error) {
	row := q.db.QueryRow(ctx, createIdea,
		arg.UserID,
		arg.Title,
		arg.Context,
		arg.Notes,
		arg.References,
		arg.Priority,
		arg.Status,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Context,
		&i.Notes,
		&i.References,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceDigestArticleID,
	)
	return i, err
}

const ensureTagForIdea = `-- name: EnsureTagForIdea :one
INSERT INTO tags (user_id, label)
VALUES ($1, $2)
ON CONFLICT (user_id, label) DO NOTHING
RETURNING id, user_id, label, created_at
`

type EnsureTagForIdeaParams struct {
	UserID pgtype.UUID
	Label  string
}

func (q *Queries) EnsureTagForIdea(ctx context.Context, arg EnsureTagForIdeaParams) (Tag, error) {
	row := q.db.QueryRow(ctx, ensureTagForIdea, arg.UserID, arg.Label)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getIdeaByID = `-- name: GetIdeaByID :one
SELECT id, user_id, title, context, notes, "references", priority, status, created_at, updated_at, source_digest_article_id FROM ideas WHERE id = $1
`

func (q *Queries) GetIdeaByID(ctx context.Context, id pgtype.UUID) (Idea, error) {
	row := q.db.QueryRow(ctx, getIdeaByID, id)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Context,
		&i.Notes,
		&i.References,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceDigestArticleID,
	)
	return i, err
}

const listIdeaTagsByIdeaID = `-- name: ListIdeaTagsByIdeaID :many
SELECT t.label FROM idea_tags it
JOIN tags t ON t.id = it.tag_id
WHERE it.idea_id = $1
ORDER BY t.label
`

func (q *Queries) ListIdeaTagsByIdeaID(ctx context.Context, ideaID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listIdeaTagsByIdeaID, ideaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdeaTagsByIdeaIDs = `-- name: ListIdeaTagsByIdeaIDs :many
SELECT it.idea_id, t.label FROM idea_tags it
JOIN tags t ON t.id = it.tag_id
WHERE it.idea_id = ANY($1::uuid[])
ORDER BY t.label
`

type ListIdeaTagsByIdeaIDsRow struct {
	IdeaID pgtype.UUID
	Label  string
}

func (q *Queries) ListIdeaTagsByIdeaIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListIdeaTagsByIdeaIDsRow, error) {
	rows, err := q.db.Query(ctx, listIdeaTagsByIdeaIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdeaTagsByIdeaIDsRow
	for rows.Next() {
		var i ListIdeaTagsByIdeaIDsRow
		if err := rows.Scan(&i.IdeaID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdeasByUser = `-- name: ListIdeasByUser :many
SELECT id, user_id, title, context, notes, "references", priority, status, created_at, updated_at, source_digest_article_id FROM ideas
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIdeasByUser(ctx context.Context, userID pgtype.UUID) ([]Idea, error) {
	rows, err := q.db.Query(ctx, listIdeasByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Context,
			&i.Notes,
			&i.References,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceDigestArticleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIdeaTag = `-- name: RemoveIdeaTag :exec
DELETE FROM idea_tags
WHERE tag_id = $1 AND idea_id = $2
`

type RemoveIdeaTagParams struct {
	TagID  pgtype.UUID
	IdeaID pgtype.UUID
}

func (q *Queries) RemoveIdeaTag(ctx context.Context, arg RemoveIdeaTagParams) error {
	_, err := q.db.Exec(ctx, removeIdeaTag, arg.TagID, arg.IdeaID)
	return err
}

const softDeleteIdea = `-- name: SoftDeleteIdea :exec
UPDATE ideas SET status = 'archived', updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteIdea(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteIdea, id)
	return err
}

const updateIdea = `-- name: UpdateIdea :one
UPDATE ideas
SET title = COALESCE($2, title),
    context = COALESCE($3, context),
    notes = COALESCE($4, notes),
    "references" = COALESCE($5, "references"),
    priority = COALESCE($6, priority),
    status = COALESCE($7, status),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, context, notes, "references", priority, status, created_at, updated_at, source_digest_article_id
`

type UpdateIdeaParams struct {
	ID         pgtype.UUID
	Title      string
	Context    *string
	Notes      *string
	References *string
	Priority   string
	Status     string
}

func (q *Queries) UpdateIdea(ctx context.Context, arg UpdateIdeaParams) (Idea, error) {
	row := q.db.QueryRow(ctx, updateIdea,
		arg.ID,
		arg.Title,
		arg.Context,
		arg.Notes,
		arg.References,
		arg.Priority,
		arg.Status,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Context,
		&i.Notes,
		&i.References,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceDigestArticleID,
	)
	return i, err
}
