// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rodrigo-militao/forge/internal/core/domain"
)

const claimNextJob = `-- name: ClaimNextJob :one
WITH next_job AS (
    SELECT id FROM jobs
    WHERE status = 'pending'
       OR (status = 'processing' AND updated_at < now() - interval '10 minutes')
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET status = 'processing', updated_at = now()
FROM next_job
WHERE jobs.id = next_job.id
RETURNING jobs.id, jobs.user_id, jobs.type, jobs.status, jobs.payload, jobs.error, jobs.created_at, jobs.updated_at
`

func (q *Queries) ClaimNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (user_id, type, payload)
VALUES ($1, $2, $3)
RETURNING id, user_id, type, status, payload, error, created_at, updated_at
`

type CreateJobParams struct {
	UserID  pgtype.UUID
	Type    string
	Payload []byte
}

// Async job queue (ADR 0028)
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.UserID, arg.Type, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveDigestJob = `-- name: FindActiveDigestJob :one
SELECT id, user_id, type, status, payload, error, created_at, updated_at FROM jobs
WHERE user_id = $1
  AND type = 'curate_digest'
  AND status IN ('pending', 'processing')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) FindActiveDigestJob(ctx context.Context, userID pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, findActiveDigestJob, userID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, type, status, payload, error, created_at, updated_at FROM jobs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJobsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListJobsByUser(ctx context.Context, arg ListJobsByUserParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Payload,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2, error = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, type, status, payload, error, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID
	Status domain.JobStatus
	Error  *string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status, arg.Error)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
