// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rodrigo-militao/forge/internal/core/domain"
)

type GeneratedContent struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Product      domain.ContentProduct
	Status       domain.ContentStatus
	SourceType   *string
	Title        *string
	BodyMarkdown *string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Job struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Status    domain.JobStatus
	Payload   []byte
	Error     *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Source struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Type      string
	Config    []byte
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Topic struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Topic        string
	ThemeArea    *string
	Format       *string
	OneLinePitch *string
	Enabled      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UsageCounter struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Month     pgtype.Date
	Count     int32
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	PlanoAtivo   bool
	Locale       domain.Locale
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type VoiceRoutingConfig struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ThemeArea string
	Format    string
	Voice     string
	CreatedAt pgtype.Timestamptz
}
