// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rodrigo-militao/forge/internal/core/domain"
)

type ArticleCategory struct {
	CategoryID pgtype.UUID
	ArticleID  pgtype.UUID
}

type Category struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Label     string
	CreatedAt pgtype.Timestamptz
}

type ContentTag struct {
	TagID     pgtype.UUID
	ContentID pgtype.UUID
}

type DigestArticleTag struct {
	TagID     pgtype.UUID
	ArticleID pgtype.UUID
}

type DigestInterest struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Label     string
	CreatedAt pgtype.Timestamptz
	Enabled   bool
}

type GeneratedContent struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Product      domain.ContentProduct
	Status       domain.ContentStatus
	SourceType   *string
	Title        *string
	BodyMarkdown *string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Origin       string
	DeletedAt    pgtype.Timestamptz
	Category     *string
	Tags         []string
	Categories   []string
}

type Job struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Status    domain.JobStatus
	Payload   []byte
	Error     *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type NewsletterArticle struct {
	NewsletterID    pgtype.UUID
	DigestArticleID pgtype.UUID
	AddedAt         pgtype.Timestamptz
}

type NewsletterEdition struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	Introduction string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Category     *string
}

type NewsletterEditionTag struct {
	EditionID pgtype.UUID
	TagID     pgtype.UUID
}

type Source struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Type      string
	Config    []byte
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Label     string
	CreatedAt pgtype.Timestamptz
}

type Topic struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Topic        string
	ThemeArea    *string
	Format       *string
	OneLinePitch *string
	Enabled      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UsageCounter struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Month     pgtype.Date
	Count     int32
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                      pgtype.UUID
	Email                   string
	PasswordHash            string
	Name                    string
	PlanoAtivo              bool
	Locale                  domain.Locale
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	MaxActiveSources        int32
	MaxActiveInterests      int32
	RestrictSearchToSources bool
	MaxMonthlyGenerations   int32
	ThemePreference         domain.ThemePreference
}

type VoiceRoutingConfig struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ThemeArea string
	Format    string
	Voice     string
	CreatedAt pgtype.Timestamptz
}
