// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: references.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rodrigo-militao/forge/internal/core/domain"
)

const attachReferenceToContent = `-- name: AttachReferenceToContent :exec
INSERT INTO content_references (content_id, reference_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachReferenceToContentParams struct {
	ContentID   pgtype.UUID
	ReferenceID pgtype.UUID
}

func (q *Queries) AttachReferenceToContent(ctx context.Context, arg AttachReferenceToContentParams) error {
	_, err := q.db.Exec(ctx, attachReferenceToContent, arg.ContentID, arg.ReferenceID)
	return err
}

const attachReferenceToIdea = `-- name: AttachReferenceToIdea :exec
INSERT INTO idea_references (idea_id, reference_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachReferenceToIdeaParams struct {
	IdeaID      pgtype.UUID
	ReferenceID pgtype.UUID
}

func (q *Queries) AttachReferenceToIdea(ctx context.Context, arg AttachReferenceToIdeaParams) error {
	_, err := q.db.Exec(ctx, attachReferenceToIdea, arg.IdeaID, arg.ReferenceID)
	return err
}

const createReference = `-- name: CreateReference :one
INSERT INTO "references" (user_id, url, title, description, source_name, reference_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, url, title, description, source_name, reference_type, created_at, updated_at
`

type CreateReferenceParams struct {
	UserID        pgtype.UUID
	Url           string
	Title         *string
	Description   *string
	SourceName    *string
	ReferenceType domain.ReferenceType
}

func (q *Queries) CreateReference(ctx context.Context, arg CreateReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, createReference,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.SourceName,
		arg.ReferenceType,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.SourceName,
		&i.ReferenceType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReference = `-- name: DeleteReference :exec
DELETE FROM "references" WHERE id = $1
`

func (q *Queries) DeleteReference(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReference, id)
	return err
}

const detachReferenceFromContent = `-- name: DetachReferenceFromContent :exec
DELETE FROM content_references WHERE content_id = $1 AND reference_id = $2
`

type DetachReferenceFromContentParams struct {
	ContentID   pgtype.UUID
	ReferenceID pgtype.UUID
}

func (q *Queries) DetachReferenceFromContent(ctx context.Context, arg DetachReferenceFromContentParams) error {
	_, err := q.db.Exec(ctx, detachReferenceFromContent, arg.ContentID, arg.ReferenceID)
	return err
}

const detachReferenceFromIdea = `-- name: DetachReferenceFromIdea :exec
DELETE FROM idea_references WHERE idea_id = $1 AND reference_id = $2
`

type DetachReferenceFromIdeaParams struct {
	IdeaID      pgtype.UUID
	ReferenceID pgtype.UUID
}

func (q *Queries) DetachReferenceFromIdea(ctx context.Context, arg DetachReferenceFromIdeaParams) error {
	_, err := q.db.Exec(ctx, detachReferenceFromIdea, arg.IdeaID, arg.ReferenceID)
	return err
}

const getReferenceByID = `-- name: GetReferenceByID :one
SELECT id, user_id, url, title, description, source_name, reference_type, created_at, updated_at FROM "references" WHERE id = $1
`

func (q *Queries) GetReferenceByID(ctx context.Context, id pgtype.UUID) (Reference, error) {
	row := q.db.QueryRow(ctx, getReferenceByID, id)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.SourceName,
		&i.ReferenceType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReferencesByContent = `-- name: ListReferencesByContent :many
SELECT r.id, r.user_id, r.url, r.title, r.description, r.source_name, r.reference_type, r.created_at, r.updated_at FROM "references" r
JOIN content_references cr ON cr.reference_id = r.id
WHERE cr.content_id = $1
ORDER BY cr.created_at DESC
`

func (q *Queries) ListReferencesByContent(ctx context.Context, contentID pgtype.UUID) ([]Reference, error) {
	rows, err := q.db.Query(ctx, listReferencesByContent, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reference
	for rows.Next() {
		var i Reference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SourceName,
			&i.ReferenceType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencesByIdea = `-- name: ListReferencesByIdea :many
SELECT r.id, r.user_id, r.url, r.title, r.description, r.source_name, r.reference_type, r.created_at, r.updated_at FROM "references" r
JOIN idea_references ir ON ir.reference_id = r.id
WHERE ir.idea_id = $1
ORDER BY ir.created_at DESC
`

func (q *Queries) ListReferencesByIdea(ctx context.Context, ideaID pgtype.UUID) ([]Reference, error) {
	rows, err := q.db.Query(ctx, listReferencesByIdea, ideaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reference
	for rows.Next() {
		var i Reference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SourceName,
			&i.ReferenceType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencesByUser = `-- name: ListReferencesByUser :many
SELECT id, user_id, url, title, description, source_name, reference_type, created_at, updated_at FROM "references" WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReferencesByUser(ctx context.Context, userID pgtype.UUID) ([]Reference, error) {
	rows, err := q.db.Query(ctx, listReferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reference
	for rows.Next() {
		var i Reference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SourceName,
			&i.ReferenceType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReference = `-- name: UpdateReference :one
UPDATE "references"
SET url = COALESCE($2, url),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    source_name = COALESCE($5, source_name),
    reference_type = COALESCE($6, reference_type),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, url, title, description, source_name, reference_type, created_at, updated_at
`

type UpdateReferenceParams struct {
	ID            pgtype.UUID
	Url           string
	Title         *string
	Description   *string
	SourceName    *string
	ReferenceType domain.ReferenceType
}

func (q *Queries) UpdateReference(ctx context.Context, arg UpdateReferenceParams) (Reference, error) {
	row := q.db.QueryRow(ctx, updateReference,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.SourceName,
		arg.ReferenceType,
	)
	var i Reference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.SourceName,
		&i.ReferenceType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
