// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (user_id, name, type, config)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, type, config, enabled, created_at, updated_at
`

type CreateSourceParams struct {
	UserID pgtype.UUID
	Name   string
	Type   string
	Config []byte
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const listSourcesByUser = `-- name: ListSourcesByUser :many
SELECT id, user_id, name, type, config, enabled, created_at, updated_at FROM sources WHERE user_id = $1 ORDER BY name
`

// Content sources (Digest product)
func (q *Queries) ListSourcesByUser(ctx context.Context, userID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET name = $2, type = $3, config = $4, enabled = $5, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, type, config, enabled, created_at, updated_at
`

type UpdateSourceParams struct {
	ID      pgtype.UUID
	Name    string
	Type    string
	Config  []byte
	Enabled bool
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
