// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (user_id, topic, theme_area, format, one_line_pitch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, topic, theme_area, format, one_line_pitch, enabled, created_at, updated_at
`

type CreateTopicParams struct {
	UserID       pgtype.UUID
	Topic        string
	ThemeArea    *string
	Format       *string
	OneLinePitch *string
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.UserID,
		arg.Topic,
		arg.ThemeArea,
		arg.Format,
		arg.OneLinePitch,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Topic,
		&i.ThemeArea,
		&i.Format,
		&i.OneLinePitch,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopicsByUser = `-- name: ListTopicsByUser :many
SELECT id, user_id, topic, theme_area, format, one_line_pitch, enabled, created_at, updated_at FROM topics WHERE user_id = $1 AND enabled = true ORDER BY created_at DESC
`

// Topics (Compose product)
func (q *Queries) ListTopicsByUser(ctx context.Context, userID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Topic,
			&i.ThemeArea,
			&i.Format,
			&i.OneLinePitch,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topicHistory = `-- name: TopicHistory :many
SELECT id, user_id, topic, theme_area, format, one_line_pitch, enabled, created_at, updated_at FROM topics
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type TopicHistoryParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) TopicHistory(ctx context.Context, arg TopicHistoryParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, topicHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Topic,
			&i.ThemeArea,
			&i.Format,
			&i.OneLinePitch,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
