// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_counters.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageCounter = `-- name: GetUsageCounter :one
SELECT coalesce(count, 0)::int FROM usage_counters
WHERE user_id = $1 AND month = $2::date
`

type GetUsageCounterParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Date
}

func (q *Queries) GetUsageCounter(ctx context.Context, arg GetUsageCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUsageCounter, arg.UserID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertUsageCounter = `-- name: UpsertUsageCounter :one
INSERT INTO usage_counters (user_id, month, count)
VALUES ($1, $2::date, 1)
ON CONFLICT (user_id, month)
DO UPDATE SET count = usage_counters.count + 1
RETURNING count
`

type UpsertUsageCounterParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Date
}

func (q *Queries) UpsertUsageCounter(ctx context.Context, arg UpsertUsageCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertUsageCounter, arg.UserID, arg.Column2)
	var count int32
	err := row.Scan(&count)
	return count, err
}
