ALTER TABLE users ADD COLUMN max_active_sources INTEGER NOT NULL DEFAULT 10;
ALTER TABLE users ADD COLUMN max_active_interests INTEGER NOT NULL DEFAULT 5;
ALTER TABLE digest_interests ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT true;
