// Package domain holds Compose-specific entities and business logic.
package domain

import (
	"time"

	"github.com/google/uuid"
)

// ThemeArea is the subject category of an article topic.
type ThemeArea string

const (
	ThemeBackendInfra      ThemeArea = "backend_infra"
	ThemeAI                ThemeArea = "ai"
	ThemePersonalDev       ThemeArea = "personal_dev"
	ThemeContentCreation   ThemeArea = "content_creation"
)

// Format is the structural style of an article.
type Format string

const (
	FormatTutorial  Format = "tutorial"
	FormatDeepDive  Format = "deep_dive"
	FormatFramework Format = "framework"
	FormatEssay     Format = "essay"
)

// Topic is an article concept generated by the Topic Generator.
type Topic struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Topic             string
	ThemeArea         ThemeArea
	Format            Format
	OneLinePitch      string
	TargetLengthWords int
	Enabled           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// HistoryEntry records a previously generated topic to avoid repetition.
type HistoryEntry struct {
	Topic       Topic
	GeneratedAt time.Time
}
